# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: dark
  theme_night: true
  font: 'Native'
  font_size: S




# Site header

header:
  navbar:
    enable: false
    align: r
    show_logo: false
    show_language: false
    show_day_night: true
    show_search: false
    highlight_active_link: true



# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false

  repository:
    url: 'https://github.com/GiaLuQuant/myBlog_2.0'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle





